'use client'

import { useAppStore, type Recipe } from '@/lib/store'
import {
  ArrowLeft,
  Clock,
  Users,
  Flame,
  Heart,
  Share2,
  ChevronRight,
  ChevronLeft,
  CheckCircle2,
  Circle,
  Timer,
  BookOpen,
  Leaf,
  Drumstick,
} from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { Progress } from '@/components/ui/progress'
import { useState, useEffect, useCallback } from 'react'
import { toast } from '@/hooks/use-toast'

export default function DetailView() {
  const {
    setCurrentView,
    previousView,
    selectedRecipe,
    cookingStep,
    setCookingStep,
    favorites,
    setFavorites,
    recipeImageUrls,
  } = useAppStore()

  const [cookingMode, setCookingMode] = useState(false)
  const [timerSeconds, setTimerSeconds] = useState(0)
  const [timerActive, setTimerActive] = useState(false)

  const recipe = selectedRecipe
  const isFavorited = recipe ? favorites.some((f) => f.title === recipe.title) : false
  const recipeImage = recipe ? recipeImageUrls[recipe.id] : null

  // Timer logic
  useEffect(() => {
    let interval: ReturnType<typeof setInterval> | null = null
    if (timerActive && timerSeconds > 0) {
      interval = setInterval(() => {
        setTimerSeconds((prev) => {
          if (prev <= 1) {
            setTimerActive(false)
            toast({ title: 'Timer done! ⏰' })
            return 0
          }
          return prev - 1
        })
      }, 1000)
    }
    return () => {
      if (interval) clearInterval(interval)
    }
  }, [timerActive, timerSeconds])

  const startTimer = (minutes: number) => {
    setTimerSeconds(minutes * 60)
    setTimerActive(true)
  }

  const formatTime = (seconds: number) => {
    const m = Math.floor(seconds / 60)
    const s = seconds % 60
    return `${m}:${s.toString().padStart(2, '0')}`
  }

  const handleFavorite = useCallback(async () => {
    if (!recipe) return
    try {
      if (isFavorited) {
        const fav = favorites.find((f) => f.title === recipe.title)
        if (fav) {
          await fetch(`/api/favorites?id=${fav.id}`, { method: 'DELETE' })
          setFavorites(favorites.filter((f) => f.id !== fav.id))
          toast({ title: 'Removed from favorites' })
        }
      } else {
        const res = await fetch('/api/favorites', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ recipe }),
        })
        if (res.ok) {
          const data = await res.json()
          setFavorites([...favorites, data.favorite])
          toast({ title: 'Added to favorites! ❤️' })
        }
      }
    } catch (e) {
      console.error(e)
    }
  }, [recipe, isFavorited, favorites, setFavorites])

  const handleShare = useCallback(async () => {
    if (!recipe) return
    const vegBadge = recipe.isVegetarian ? '🟢 Veg' : '🔴 Non-Veg'
    const shareText = `🍳 ${recipe.title}\n${vegBadge}\n⏱ ${recipe.prepTime} prep · ${recipe.cookTime} cook\n👥 Serves ${recipe.servings}\n\n🥘 Ingredients:\n${recipe.ingredients.map((i) => `• ${i}`).join('\n')}\n\n👨‍🍳 Steps:\n${recipe.steps.map((s, i) => `${i + 1}. ${s}`).join('\n')}\n\nGenerated by CookSnap`

    if (navigator.share) {
      try {
        await navigator.share({ title: recipe.title, text: shareText })
      } catch { /* cancelled */ }
    } else {
      await navigator.clipboard.writeText(shareText)
      toast({ title: 'Recipe copied to clipboard!' })
    }
  }, [recipe])

  if (!recipe) {
    return (
      <div className="view-transition min-h-screen flex items-center justify-center">
        <p>No recipe selected</p>
        <Button onClick={() => setCurrentView(previousView === 'detail' ? 'home' : previousView)} className="ml-2">
          Go Back
        </Button>
      </div>
    )
  }

  const progressPercent = ((cookingStep + 1) / recipe.steps.length) * 100

  return (
    <div className="view-transition min-h-screen flex flex-col">
      {/* Header */}
      <div className="sticky top-0 z-10 bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/80 border-b">
        <div className="flex items-center justify-between px-4 py-3">
          <Button
            variant="ghost"
            size="icon"
            onClick={() => {
              if (cookingMode) {
                setCookingMode(false)
                setCookingStep(0)
              } else {
                setCurrentView(previousView === 'detail' ? 'home' : previousView)
              }
            }}
          >
            <ArrowLeft className="w-5 h-5" />
          </Button>
          <h1 className="text-lg font-semibold truncate max-w-[200px]">
            {cookingMode ? `Step ${cookingStep + 1}/${recipe.steps.length}` : recipe.title}
          </h1>
          <div className="flex gap-1">
            <Button variant="ghost" size="icon" onClick={handleFavorite}>
              <Heart
                className={`w-5 h-5 ${
                  isFavorited ? 'fill-red-500 text-red-500' : 'text-foreground'
                }`}
              />
            </Button>
            <Button variant="ghost" size="icon" onClick={handleShare}>
              <Share2 className="w-5 h-5" />
            </Button>
          </div>
        </div>
        {cookingMode && (
          <div className="px-4 pb-2">
            <Progress value={progressPercent} className="h-2" />
          </div>
        )}
      </div>

      {/* Content */}
      {cookingMode ? (
        /* Cooking Mode */
        <div className="flex-1 flex flex-col px-4 py-6">
          {timerActive && (
            <div className="bg-orange-50 border border-orange-200 rounded-xl p-4 mb-6 text-center">
              <p className="text-sm text-orange-600 mb-1">Timer</p>
              <p className="text-4xl font-mono font-bold text-orange-700">
                {formatTime(timerSeconds)}
              </p>
              <Button
                variant="ghost"
                size="sm"
                className="mt-2 text-orange-600"
                onClick={() => { setTimerActive(false); setTimerSeconds(0) }}
              >
                Stop Timer
              </Button>
            </div>
          )}

          <div className="flex-1 flex flex-col items-center justify-center text-center max-w-lg mx-auto">
            <div className="w-16 h-16 rounded-full bg-orange-100 flex items-center justify-center mb-6">
              <span className="text-3xl font-bold text-orange-600">{cookingStep + 1}</span>
            </div>
            <p className="text-xl leading-relaxed text-foreground mb-8">
              {recipe.steps[cookingStep]}
            </p>

            <div className="flex gap-2 mb-8">
              {[1, 3, 5, 10].map((min) => (
                <Button
                  key={min}
                  variant="outline"
                  size="sm"
                  className="border-orange-200 text-orange-600"
                  onClick={() => startTimer(min)}
                >
                  <Timer className="w-3 h-3 mr-1" />
                  {min}m
                </Button>
              ))}
            </div>
          </div>

          <div className="flex items-center justify-between pb-8 pt-4">
            <Button
              variant="outline"
              onClick={() => setCookingStep(Math.max(0, cookingStep - 1))}
              disabled={cookingStep === 0}
              className="border-orange-200"
            >
              <ChevronLeft className="w-4 h-4 mr-1" />
              Previous
            </Button>
            {cookingStep < recipe.steps.length - 1 ? (
              <Button
                onClick={() => setCookingStep(cookingStep + 1)}
                className="bg-orange-500 hover:bg-orange-600 text-white"
              >
                Next
                <ChevronRight className="w-4 h-4 ml-1" />
              </Button>
            ) : (
              <Button
                onClick={() => {
                  setCookingMode(false)
                  setCookingStep(0)
                  toast({ title: 'Enjoy your meal! 🎉' })
                }}
                className="bg-green-500 hover:bg-green-600 text-white"
              >
                <CheckCircle2 className="w-4 h-4 mr-1" />
                Done!
              </Button>
            )}
          </div>
        </div>
      ) : (
        /* Detail View */
        <div className="flex-1 overflow-y-auto">
          {/* Hero with actual image */}
          <div className="h-48 relative overflow-hidden">
            {recipeImage ? (
              <img
                src={recipeImage}
                alt={recipe.title}
                className="w-full h-full object-cover"
              />
            ) : (
              <div className="w-full h-full bg-gradient-to-br from-orange-300 via-amber-200 to-orange-400 flex items-center justify-center">
                <div className="text-center">
                  <div className="w-16 h-16 mx-auto mb-2 rounded-full bg-white/30 flex items-center justify-center">
                    <Flame className="w-8 h-8 text-white" />
                  </div>
                  <span className="text-sm text-white/90 font-medium">Cooking up an image...</span>
                </div>
              </div>
            )}
            {/* Veg/Non-veg badge on image */}
            <div className="absolute top-3 left-3">
              <div className={`px-2.5 py-1 rounded-md text-xs font-bold flex items-center gap-1 ${
                recipe.isVegetarian ? 'bg-green-500 text-white' : 'bg-red-500 text-white'
              }`}>
                {recipe.isVegetarian ? (
                  <><Leaf className="w-3.5 h-3.5" /> Vegetarian</>
                ) : (
                  <><Drumstick className="w-3.5 h-3.5" /> Non-Vegetarian</>
                )}
              </div>
            </div>
          </div>

          <div className="px-4 py-5 space-y-6">
            {/* Title & Meta */}
            <div>
              <h2 className="text-2xl font-bold text-foreground mb-2">{recipe.title}</h2>
              <div className="flex items-center gap-3 flex-wrap">
                <Badge className="bg-orange-100 text-orange-700">
                  {recipe.cuisine}
                </Badge>
                <Badge className={recipe.isVegetarian ? 'bg-green-100 text-green-700' : 'bg-red-100 text-red-700'}>
                  {recipe.isVegetarian ? (
                    <><Leaf className="w-3 h-3 mr-1" /> Veg</>
                  ) : (
                    <><Drumstick className="w-3 h-3 mr-1" /> Non-Veg</>
                  )}
                </Badge>
                <div className="flex items-center gap-1 text-sm text-muted-foreground">
                  <Clock className="w-3.5 h-3.5" />
                  <span>{recipe.prepTime} prep</span>
                </div>
                <div className="flex items-center gap-1 text-sm text-muted-foreground">
                  <Flame className="w-3.5 h-3.5" />
                  <span>{recipe.cookTime}</span>
                </div>
                <div className="flex items-center gap-1 text-sm text-muted-foreground">
                  <Users className="w-3.5 h-3.5" />
                  <span>{recipe.servings} servings</span>
                </div>
              </div>
              <div className="flex flex-wrap gap-1 mt-2">
                {recipe.tags?.map((tag) => (
                  <Badge key={tag} variant="outline" className="text-xs border-orange-200 text-orange-600">
                    {tag}
                  </Badge>
                ))}
              </div>
            </div>

            {/* Ingredients */}
            <div>
              <h3 className="text-lg font-semibold mb-3 flex items-center gap-2">
                <span className="text-xl">🥘</span> Ingredients
              </h3>
              <div className="space-y-2">
                {recipe.ingredients.map((ing, i) => (
                  <div
                    key={i}
                    className="flex items-center gap-3 p-2 rounded-lg hover:bg-orange-50 transition-colors"
                  >
                    <Circle className="w-4 h-4 text-orange-400 flex-shrink-0" />
                    <span className="text-sm">{ing}</span>
                  </div>
                ))}
              </div>
            </div>

            {/* Steps */}
            <div>
              <h3 className="text-lg font-semibold mb-3 flex items-center gap-2">
                <span className="text-xl">👨‍🍳</span> Instructions
              </h3>
              <div className="space-y-3">
                {recipe.steps.map((step, i) => (
                  <div key={i} className="flex gap-3">
                    <div className="w-7 h-7 rounded-full bg-orange-500 text-white flex items-center justify-center text-xs font-bold flex-shrink-0 mt-0.5">
                      {i + 1}
                    </div>
                    <p className="text-sm leading-relaxed text-foreground pt-1">{step}</p>
                  </div>
                ))}
              </div>
            </div>

            {/* Start Cooking Button */}
            <div className="pb-6">
              <Button
                onClick={() => { setCookingMode(true); setCookingStep(0) }}
                className="w-full bg-gradient-to-r from-orange-500 to-amber-500 hover:from-orange-600 hover:to-amber-600 text-white font-semibold text-base py-6 rounded-2xl shadow-lg"
              >
                <BookOpen className="w-5 h-5 mr-2" />
                Start Cooking Mode
              </Button>
              <p className="text-center text-xs text-muted-foreground mt-2">
                Step-by-step mode with built-in timer
              </p>
            </div>
          </div>
        </div>
      )}
    </div>
  )
}
