'use client'

import { useAppStore, type FavoriteRecipe } from '@/lib/store'
import { ArrowLeft, Heart, Trash2, Share2, Clock, Users, Flame, Leaf, Drumstick } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { Card, CardContent } from '@/components/ui/card'
import { useState, useEffect } from 'react'
import { toast } from '@/hooks/use-toast'

export default function FavoritesView() {
  const { setCurrentView, favorites, setFavorites, setSelectedRecipe, recipeImageUrls } = useAppStore()
  const [isLoading, setIsLoading] = useState(true)

  useEffect(() => {
    loadFavorites()
  }, [])

  const loadFavorites = async () => {
    setIsLoading(true)
    try {
      const res = await fetch('/api/favorites')
      if (res.ok) {
        const data = await res.json()
        setFavorites(data.favorites || [])
      }
    } catch (e) {
      console.error(e)
    } finally {
      setIsLoading(false)
    }
  }

  const handleDelete = async (id: string) => {
    try {
      const res = await fetch(`/api/favorites?id=${id}`, { method: 'DELETE' })
      if (res.ok) {
        setFavorites(favorites.filter((f) => f.id !== id))
        toast({ title: 'Removed from favorites' })
      }
    } catch (e) {
      console.error(e)
      toast({ title: 'Failed to remove', variant: 'destructive' })
    }
  }

  const handleShare = async (recipe: FavoriteRecipe) => {
    const vegBadge = recipe.isVegetarian ? '🟢 Veg' : '🔴 Non-Veg'
    const shareText = `🍳 ${recipe.title}\n${vegBadge}\n⏱ ${recipe.prepTime} prep · ${recipe.cookTime} cook\n👥 Serves ${recipe.servings}\n\n🥘 Ingredients:\n${(Array.isArray(recipe.ingredients) ? recipe.ingredients : []).map((i: string) => `• ${i}`).join('\n')}\n\n👨‍🍳 Steps:\n${(Array.isArray(recipe.steps) ? recipe.steps : []).map((s: string, i: number) => `${i + 1}. ${s}`).join('\n')}\n\nGenerated by CookSnap`

    if (navigator.share) {
      try {
        await navigator.share({ title: recipe.title, text: shareText })
      } catch { /* cancelled */ }
    } else {
      await navigator.clipboard.writeText(shareText)
      toast({ title: 'Recipe copied to clipboard!' })
    }
  }

  const openRecipe = (recipe: FavoriteRecipe) => {
    setSelectedRecipe({
      id: recipe.id,
      title: recipe.title,
      cuisine: recipe.cuisine,
      cookTime: recipe.cookTime,
      prepTime: recipe.prepTime,
      servings: recipe.servings,
      difficulty: recipe.difficulty,
      isVegetarian: recipe.isVegetarian ?? false,
      ingredients: Array.isArray(recipe.ingredients) ? recipe.ingredients : [],
      steps: Array.isArray(recipe.steps) ? recipe.steps : [],
      tags: Array.isArray(recipe.tags) ? recipe.tags : [],
      imagePrompt: recipe.imagePrompt,
      imageUrl: recipe.imageUrl,
    })
    setCurrentView('detail')
  }

  return (
    <div className="view-transition min-h-screen flex flex-col">
      {/* Header */}
      <div className="sticky top-0 z-10 bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/80 border-b">
        <div className="flex items-center justify-between px-4 py-3">
          <div className="flex items-center gap-3">
            <Button
              variant="ghost"
              size="icon"
              onClick={() => setCurrentView('home')}
            >
              <ArrowLeft className="w-5 h-5" />
            </Button>
            <div>
              <h1 className="text-lg font-semibold">My Favorites</h1>
              <p className="text-xs text-muted-foreground">{favorites.length} saved recipes</p>
            </div>
          </div>
          <Heart className="w-5 h-5 text-red-500 fill-red-500" />
        </div>
      </div>

      {/* Content */}
      <div className="flex-1 px-4 py-4 space-y-4 pb-8">
        {isLoading ? (
          <div className="flex items-center justify-center py-12">
            <div className="w-8 h-8 border-2 border-orange-400 border-t-transparent rounded-full animate-spin" />
          </div>
        ) : favorites.length === 0 ? (
          <div className="flex flex-col items-center justify-center py-16 text-center">
            <span className="text-6xl mb-4">💝</span>
            <h2 className="text-xl font-semibold mb-2">No favorites yet</h2>
            <p className="text-muted-foreground text-sm mb-4">
              Save recipes you love for quick access later
            </p>
            <Button
              onClick={() => setCurrentView('home')}
              className="bg-orange-500 hover:bg-orange-600 text-white"
            >
              Find Recipes
            </Button>
          </div>
        ) : (
          favorites.map((recipe, index) => (
            <Card
              key={recipe.id}
              className="overflow-hidden cursor-pointer hover:shadow-lg transition-all active:scale-[0.99] border-orange-100 slide-up"
              style={{ animationDelay: `${index * 80}ms` }}
              onClick={() => openRecipe(recipe)}
            >
              <div className="h-28 flex items-center relative overflow-hidden bg-gradient-to-br from-orange-400 to-amber-500">
                {recipeImageUrls[recipe.id] ? (
                  <img
                    src={recipeImageUrls[recipe.id]}
                    alt={recipe.title}
                    className="w-full h-full object-cover"
                  />
                ) : (
                  <div className="w-full h-full flex items-center justify-center bg-gradient-to-br from-orange-300 via-amber-200 to-orange-400">
                    <div className="w-10 h-10 rounded-full bg-white/30 flex items-center justify-center">
                      <Flame className="w-5 h-5 text-white" />
                    </div>
                  </div>
                )}

                {/* Veg/Non-veg badge */}
                <div className="absolute top-2 left-2">
                  <div className={`px-1.5 py-0.5 rounded text-[10px] font-bold flex items-center gap-0.5 ${
                    (recipe.isVegetarian ?? false) ? 'bg-green-500 text-white' : 'bg-red-500 text-white'
                  }`}>
                    {(recipe.isVegetarian ?? false) ? (
                      <><Leaf className="w-2.5 h-2.5" /> Veg</>
                    ) : (
                      <><Drumstick className="w-2.5 h-2.5" /> Non-Veg</>
                    )}
                  </div>
                </div>

                <div className="absolute top-2 right-2 flex gap-1.5">
                  <Button
                    variant="secondary"
                    size="icon"
                    className="w-7 h-7 rounded-full bg-white/90 hover:bg-white"
                    onClick={(e) => {
                      e.stopPropagation()
                      handleShare(recipe)
                    }}
                  >
                    <Share2 className="w-3.5 h-3.5 text-gray-600" />
                  </Button>
                  <Button
                    variant="secondary"
                    size="icon"
                    className="w-7 h-7 rounded-full bg-white/90 hover:bg-white"
                    onClick={(e) => {
                      e.stopPropagation()
                      handleDelete(recipe.id)
                    }}
                  >
                    <Trash2 className="w-3.5 h-3.5 text-red-500" />
                  </Button>
                </div>
                <Badge className="absolute bottom-2 left-2 bg-white/90 text-orange-700 text-xs">
                  {recipe.cuisine}
                </Badge>
              </div>

              <CardContent className="p-4">
                <h3 className="font-bold text-base mb-2">{recipe.title}</h3>
                <div className="flex items-center gap-3 text-xs text-muted-foreground">
                  <div className="flex items-center gap-1">
                    <Clock className="w-3 h-3" />
                    <span>{recipe.prepTime} + {recipe.cookTime}</span>
                  </div>
                  <div className="flex items-center gap-1">
                    <Users className="w-3 h-3" />
                    <span>{recipe.servings} servings</span>
                  </div>
                  <Badge variant="outline" className="text-xs">
                    <Flame className="w-3 h-3 mr-1" />
                    {recipe.difficulty}
                  </Badge>
                </div>
              </CardContent>
            </Card>
          ))
        )}
      </div>
    </div>
  )
}
