'use client'

import { useAppStore, type Recipe } from '@/lib/store'
import { ArrowLeft, Clock, Users, Flame, Heart, Share2, ChefHat, Leaf, Drumstick, Filter } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Card, CardContent } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import { useState, useEffect } from 'react'
import { toast } from '@/hooks/use-toast'

const difficultyColors: Record<string, string> = {
  easy: 'bg-green-100 text-green-700',
  medium: 'bg-yellow-100 text-yellow-700',
  hard: 'bg-red-100 text-red-700',
}

const cuisineList = [
  { id: 'all', label: 'All' },
  { id: 'Indian', label: '🇮🇳 Indian' },
  { id: 'Italian', label: '🇮🇹 Italian' },
  { id: 'Chinese', label: '🇨🇳 Chinese' },
  { id: 'Mexican', label: '🇲🇽 Mexican' },
  { id: 'Japanese', label: '🇯🇵 Japanese' },
  { id: 'Thai', label: '🇹🇭 Thai' },
  { id: 'Mediterranean', label: '🫒 Mediterranean' },
  { id: 'American', label: '🇺🇸 American' },
  { id: 'Korean', label: '🇰🇷 Korean' },
  { id: 'French', label: '🇫🇷 French' },
  { id: 'Middle Eastern', label: '🧆 Middle Eastern' },
]

export default function ResultsView() {
  const { setCurrentView, recipes, setSelectedRecipe, favorites, setFavorites, recipeImageUrls, setRecipeImageUrl } = useAppStore()
  const [sharing, setSharing] = useState<string | null>(null)
  const [cuisineFilter, setCuisineFilter] = useState('all')
  const [showFilters, setShowFilters] = useState(false)

  // Load favorites on mount
  useEffect(() => {
    const loadFavorites = async () => {
      try {
        const res = await fetch('/api/favorites')
        if (res.ok) {
          const data = await res.json()
          setFavorites(data.favorites || [])
        }
      } catch (e) {
        console.error(e)
      }
    }
    loadFavorites()
  }, [setFavorites])

  // Generate recipe images
  useEffect(() => {
    const generateImages = async () => {
      for (const recipe of recipes) {
        if (!recipe.imagePrompt || recipeImageUrls[recipe.id]) continue

        try {
          const res = await fetch('/api/recipes/image', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({
              prompt: recipe.imagePrompt,
              recipeId: recipe.id.replace(/[^a-zA-Z0-9-]/g, ''),
            }),
          })

          if (res.ok) {
            const data = await res.json()
            if (data.imageUrl) {
              setRecipeImageUrl(recipe.id, data.imageUrl)
            }
          }
        } catch (e) {
          console.error('Image generation error for', recipe.title, e)
        }
      }
    }

    if (recipes.length > 0) {
      generateImages()
    }
  }, [recipes, recipeImageUrls, setRecipeImageUrl])

  const isFavorited = (recipe: Recipe) =>
    favorites.some((f) => f.title === recipe.title)

  const handleFavorite = async (recipe: Recipe) => {
    try {
      if (isFavorited(recipe)) {
        const fav = favorites.find((f) => f.title === recipe.title)
        if (fav) {
          await fetch(`/api/favorites?id=${fav.id}`, { method: 'DELETE' })
          setFavorites(favorites.filter((f) => f.id !== fav.id))
          toast({ title: 'Removed from favorites' })
        }
      } else {
        const res = await fetch('/api/favorites', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ recipe }),
        })
        if (res.ok) {
          const data = await res.json()
          setFavorites([...favorites, data.favorite])
          toast({ title: 'Added to favorites! ❤️' })
        }
      }
    } catch (e) {
      console.error(e)
      toast({ title: 'Failed to update favorites', variant: 'destructive' })
    }
  }

  const handleShare = async (recipe: Recipe) => {
    setSharing(recipe.id)
    const vegBadge = recipe.isVegetarian ? '🟢 Veg' : '🔴 Non-Veg'
    const shareText = `🍳 ${recipe.title}\n${vegBadge}\n⏱ ${recipe.prepTime} prep · ${recipe.cookTime} cook\n👥 Serves ${recipe.servings}\n\nIngredients: ${recipe.ingredients.join(', ')}\n\nGenerated by CookSnap - Snap your fridge, get instant recipes!`

    if (navigator.share) {
      try {
        await navigator.share({ title: recipe.title, text: shareText })
      } catch { /* cancelled */ }
    } else {
      await navigator.clipboard.writeText(shareText)
      toast({ title: 'Recipe copied to clipboard!' })
    }
    setSharing(null)
  }

  // Apply filters
  const filteredRecipes = recipes.filter((recipe) => {
    if (cuisineFilter !== 'all' && recipe.cuisine?.toLowerCase() !== cuisineFilter.toLowerCase()) return false
    return true
  })

  const availableCuisines = [...new Set(recipes.map((r) => r.cuisine).filter(Boolean))]

  return (
    <div className="view-transition min-h-screen flex flex-col">
      {/* Header */}
      <div className="sticky top-0 z-10 bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/80 border-b">
        <div className="flex items-center justify-between px-4 py-3">
          <div className="flex items-center gap-3">
            <Button
              variant="ghost"
              size="icon"
              onClick={() => setCurrentView('confirm')}
              className="text-foreground"
            >
              <ArrowLeft className="w-5 h-5" />
            </Button>
            <div>
              <h1 className="text-lg font-semibold">Recipes For You</h1>
              <p className="text-xs text-muted-foreground">
                {filteredRecipes.length} of {recipes.length} recipes
              </p>
            </div>
          </div>
          <div className="flex gap-2">
            <Button
              variant="outline"
              size="sm"
              className={`border-orange-200 ${showFilters ? 'bg-orange-50 text-orange-700' : 'text-orange-600'}`}
              onClick={() => setShowFilters(!showFilters)}
            >
              <Filter className="w-3.5 h-3.5 mr-1" />
              Filter
            </Button>
          </div>
        </div>

        {/* Filter Bar */}
        {showFilters && (
          <div className="px-4 pb-3 space-y-3 border-t pt-3 bg-orange-50/30">
            {/* Cuisine Filter */}
            <div>
              <p className="text-xs font-semibold text-muted-foreground mb-1.5">CUISINE</p>
              <div className="flex gap-1.5 overflow-x-auto pb-1" style={{ scrollbarWidth: 'none' }}>
                <button
                  onClick={() => setCuisineFilter('all')}
                  className={`flex-shrink-0 px-3 py-1.5 rounded-full text-xs font-semibold transition-all ${
                    cuisineFilter === 'all'
                      ? 'bg-orange-500 text-white shadow-sm'
                      : 'bg-white text-gray-600 border border-gray-200'
                  }`}
                >
                  All
                </button>
                {availableCuisines.map((cuisine) => (
                  <button
                    key={cuisine}
                    onClick={() => setCuisineFilter(cuisine)}
                    className={`flex-shrink-0 px-3 py-1.5 rounded-full text-xs font-semibold transition-all ${
                      cuisineFilter === cuisine
                        ? 'bg-orange-500 text-white shadow-sm'
                        : 'bg-white text-gray-600 border border-gray-200'
                    }`}
                  >
                    {cuisine}
                  </button>
                ))}
              </div>
            </div>
          </div>
        )}
      </div>

      {/* Recipe Cards */}
      <div className="flex-1 px-4 py-4 space-y-4 pb-8">
        {filteredRecipes.map((recipe, index) => (
          <Card
            key={recipe.id}
            className="overflow-hidden cursor-pointer hover:shadow-lg transition-all active:scale-[0.99] border-orange-100 slide-up"
            style={{ animationDelay: `${index * 80}ms` }}
            onClick={() => {
              setSelectedRecipe(recipe)
              setCurrentView('detail')
            }}
          >
            {/* Recipe Image */}
            <div className="h-44 relative overflow-hidden bg-gradient-to-br from-orange-400 to-amber-500">
              {recipeImageUrls[recipe.id] ? (
                <img
                  src={recipeImageUrls[recipe.id]}
                  alt={recipe.title}
                  className="w-full h-full object-cover"
                />
              ) : (
                <div className="w-full h-full flex items-center justify-center bg-gradient-to-br from-orange-300 via-amber-200 to-orange-400">
                  <div className="text-center">
                    <div className="w-12 h-12 mx-auto mb-1 rounded-full bg-white/30 flex items-center justify-center animate-pulse">
                      <Flame className="w-6 h-6 text-white" />
                    </div>
                    <span className="text-xs text-white/90 font-medium">Cooking up an image...</span>
                  </div>
                </div>
              )}

              {/* Veg/Non-veg badge */}
              <div className="absolute top-3 left-3">
                <div className={`px-2 py-1 rounded-md text-xs font-bold flex items-center gap-1 ${
                  recipe.isVegetarian
                    ? 'bg-green-500 text-white'
                    : 'bg-red-500 text-white'
                }`}>
                  {recipe.isVegetarian ? (
                    <><Leaf className="w-3 h-3" /> Veg</>
                  ) : (
                    <><Drumstick className="w-3 h-3" /> Non-Veg</>
                  )}
                </div>
              </div>

              {/* Action buttons */}
              <div className="absolute top-3 right-3 flex gap-2">
                <Button
                  variant="secondary"
                  size="icon"
                  className="w-8 h-8 rounded-full bg-white/90 hover:bg-white"
                  onClick={(e) => {
                    e.stopPropagation()
                    handleFavorite(recipe)
                  }}
                >
                  <Heart
                    className={`w-4 h-4 ${
                      isFavorited(recipe) ? 'fill-red-500 text-red-500' : 'text-gray-600'
                    }`}
                  />
                </Button>
                <Button
                  variant="secondary"
                  size="icon"
                  className="w-8 h-8 rounded-full bg-white/90 hover:bg-white"
                  onClick={(e) => {
                    e.stopPropagation()
                    handleShare(recipe)
                  }}
                  disabled={sharing === recipe.id}
                >
                  <Share2 className="w-4 h-4 text-gray-600" />
                </Button>
              </div>

              {/* Cuisine badge */}
              <Badge className="absolute bottom-3 left-3 bg-white/90 text-orange-700 font-medium">
                {recipe.cuisine}
              </Badge>
            </div>

            <CardContent className="p-4">
              <h3 className="font-bold text-lg text-foreground mb-2">{recipe.title}</h3>

              <div className="flex items-center gap-4 text-sm text-muted-foreground mb-3">
                <div className="flex items-center gap-1">
                  <Clock className="w-3.5 h-3.5" />
                  <span>{recipe.prepTime} + {recipe.cookTime}</span>
                </div>
                <div className="flex items-center gap-1">
                  <Users className="w-3.5 h-3.5" />
                  <span>{recipe.servings} servings</span>
                </div>
                <Badge
                  variant="secondary"
                  className={`text-xs ${difficultyColors[recipe.difficulty] || difficultyColors.easy}`}
                >
                  <Flame className="w-3 h-3 mr-1" />
                  {recipe.difficulty}
                </Badge>
              </div>

              {/* Tags */}
              <div className="flex flex-wrap gap-1">
                {recipe.tags?.slice(0, 4).map((tag) => (
                  <Badge key={tag} variant="outline" className="text-xs border-orange-200 text-orange-600">
                    {tag}
                  </Badge>
                ))}
              </div>
            </CardContent>
          </Card>
        ))}

        {filteredRecipes.length === 0 && recipes.length > 0 && (
          <div className="flex flex-col items-center justify-center py-16 text-center">
            <span className="text-6xl mb-4">🔍</span>
            <h2 className="text-xl font-semibold mb-2">No recipes match filters</h2>
            <p className="text-muted-foreground text-sm mb-4">
              Try changing your cuisine filter
            </p>
            <Button
              onClick={() => setCuisineFilter('all')}
              className="bg-orange-500 hover:bg-orange-600 text-white"
            >
              Clear Filters
            </Button>
          </div>
        )}

        {recipes.length === 0 && (
          <div className="flex flex-col items-center justify-center py-16 text-center">
            <span className="text-6xl mb-4">🤔</span>
            <h2 className="text-xl font-semibold mb-2">No recipes yet</h2>
            <p className="text-muted-foreground text-sm mb-4">
              Add ingredients and generate recipes
            </p>
            <Button
              onClick={() => setCurrentView('confirm')}
              className="bg-orange-500 hover:bg-orange-600 text-white"
            >
              Add Ingredients
            </Button>
          </div>
        )}
      </div>
    </div>
  )
}
