'use client'

import { useAppStore, type Recipe } from '@/lib/store'
import { ArrowLeft, Clock, Users, Flame, Heart, Share2, ChefHat } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Card, CardContent } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import { useState, useEffect } from 'react'
import { toast } from '@/hooks/use-toast'

const difficultyColors: Record<string, string> = {
  easy: 'bg-green-100 text-green-700',
  medium: 'bg-yellow-100 text-yellow-700',
  hard: 'bg-red-100 text-red-700',
}

const foodEmojis: Record<string, string> = {
  indian: '🍛',
  italian: '🍝',
  chinese: '🥡',
  mexican: '🌮',
  japanese: '🍣',
  thai: '🍜',
  mediterranean: '🫒',
  american: '🍔',
  korean: '🥘',
  french: '🥐',
  'middle-eastern': '🧆',
  global: '🍽️',
}

export default function ResultsView() {
  const { setCurrentView, recipes, setSelectedRecipe, favorites, setFavorites } = useAppStore()
  const [sharing, setSharing] = useState<string | null>(null)

  // Load favorites on mount
  useEffect(() => {
    const loadFavorites = async () => {
      try {
        const res = await fetch('/api/favorites')
        if (res.ok) {
          const data = await res.json()
          setFavorites(data.favorites || [])
        }
      } catch (e) {
        console.error(e)
      }
    }
    loadFavorites()
  }, [setFavorites])

  const isFavorited = (recipe: Recipe) =>
    favorites.some((f) => f.title === recipe.title)

  const handleFavorite = async (recipe: Recipe) => {
    try {
      if (isFavorited(recipe)) {
        const fav = favorites.find((f) => f.title === recipe.title)
        if (fav) {
          await fetch(`/api/favorites?id=${fav.id}`, { method: 'DELETE' })
          setFavorites(favorites.filter((f) => f.id !== fav.id))
          toast({ title: 'Removed from favorites' })
        }
      } else {
        const res = await fetch('/api/favorites', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ recipe }),
        })
        if (res.ok) {
          const data = await res.json()
          setFavorites([...favorites, data.favorite])
          toast({ title: 'Added to favorites! ❤️' })
        }
      }
    } catch (e) {
      console.error(e)
      toast({ title: 'Failed to update favorites', variant: 'destructive' })
    }
  }

  const handleShare = async (recipe: Recipe) => {
    setSharing(recipe.id)
    const shareText = `🍳 ${recipe.title}\n⏱ ${recipe.prepTime} prep · ${recipe.cookTime} cook\n👥 Serves ${recipe.servings}\n\nIngredients: ${recipe.ingredients.join(', ')}\n\nGenerated by CookSnap - Snap your fridge, get instant recipes!`

    if (navigator.share) {
      try {
        await navigator.share({
          title: recipe.title,
          text: shareText,
        })
      } catch (e) {
        // User cancelled sharing
      }
    } else {
      await navigator.clipboard.writeText(shareText)
      toast({ title: 'Recipe copied to clipboard!' })
    }
    setSharing(null)
  }

  return (
    <div className="view-transition min-h-screen flex flex-col">
      {/* Header */}
      <div className="sticky top-0 z-10 bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/80 border-b">
        <div className="flex items-center justify-between px-4 py-3">
          <div className="flex items-center gap-3">
            <Button
              variant="ghost"
              size="icon"
              onClick={() => setCurrentView('confirm')}
              className="text-foreground"
            >
              <ArrowLeft className="w-5 h-5" />
            </Button>
            <div>
              <h1 className="text-lg font-semibold">Recipes For You</h1>
              <p className="text-xs text-muted-foreground">{recipes.length} recipes found</p>
            </div>
          </div>
          <Badge variant="secondary" className="bg-orange-100 text-orange-700">
            <ChefHat className="w-3 h-3 mr-1" />
            AI Generated
          </Badge>
        </div>
      </div>

      {/* Recipe Cards */}
      <div className="flex-1 px-4 py-4 space-y-4 pb-8">
        {recipes.map((recipe, index) => (
          <Card
            key={recipe.id}
            className="overflow-hidden cursor-pointer hover:shadow-lg transition-all active:scale-[0.99] border-orange-100 slide-up"
            style={{ animationDelay: `${index * 100}ms` }}
            onClick={() => {
              setSelectedRecipe(recipe)
              setCurrentView('detail')
            }}
          >
            {/* Food emoji header */}
            <div className="bg-gradient-to-br from-orange-400 to-amber-500 h-32 flex items-center justify-center relative">
              <span className="text-6xl">
                {foodEmojis[recipe.cuisine?.toLowerCase()] || '🍽️'}
              </span>
              <div className="absolute top-3 right-3 flex gap-2">
                <Button
                  variant="secondary"
                  size="icon"
                  className="w-8 h-8 rounded-full bg-white/90 hover:bg-white"
                  onClick={(e) => {
                    e.stopPropagation()
                    handleFavorite(recipe)
                  }}
                >
                  <Heart
                    className={`w-4 h-4 ${
                      isFavorited(recipe) ? 'fill-red-500 text-red-500' : 'text-gray-600'
                    }`}
                  />
                </Button>
                <Button
                  variant="secondary"
                  size="icon"
                  className="w-8 h-8 rounded-full bg-white/90 hover:bg-white"
                  onClick={(e) => {
                    e.stopPropagation()
                    handleShare(recipe)
                  }}
                  disabled={sharing === recipe.id}
                >
                  <Share2 className="w-4 h-4 text-gray-600" />
                </Button>
              </div>
              <Badge className="absolute bottom-3 left-3 bg-white/90 text-orange-700 font-medium">
                {recipe.cuisine}
              </Badge>
            </div>

            <CardContent className="p-4">
              <h3 className="font-bold text-lg text-foreground mb-2">{recipe.title}</h3>

              <div className="flex items-center gap-4 text-sm text-muted-foreground mb-3">
                <div className="flex items-center gap-1">
                  <Clock className="w-3.5 h-3.5" />
                  <span>{recipe.prepTime} + {recipe.cookTime}</span>
                </div>
                <div className="flex items-center gap-1">
                  <Users className="w-3.5 h-3.5" />
                  <span>{recipe.servings} servings</span>
                </div>
                <Badge
                  variant="secondary"
                  className={`text-xs ${difficultyColors[recipe.difficulty] || difficultyColors.easy}`}
                >
                  <Flame className="w-3 h-3 mr-1" />
                  {recipe.difficulty}
                </Badge>
              </div>

              {/* Tags */}
              <div className="flex flex-wrap gap-1">
                {recipe.tags?.slice(0, 4).map((tag) => (
                  <Badge key={tag} variant="outline" className="text-xs border-orange-200 text-orange-600">
                    {tag}
                  </Badge>
                ))}
              </div>
            </CardContent>
          </Card>
        ))}

        {recipes.length === 0 && (
          <div className="flex flex-col items-center justify-center py-16 text-center">
            <span className="text-6xl mb-4">🤔</span>
            <h2 className="text-xl font-semibold mb-2">No recipes yet</h2>
            <p className="text-muted-foreground text-sm mb-4">
              Scan your fridge or add ingredients to get started
            </p>
            <Button
              onClick={() => setCurrentView('scanner')}
              className="bg-orange-500 hover:bg-orange-600 text-white"
            >
              Scan My Fridge
            </Button>
          </div>
        )}
      </div>
    </div>
  )
}
